CREATE TABLE DateCacheValidity(Value DATETIME NOT NULL);

CREATE TABLE Lines(Id INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT NOT NULL);

CREATE TABLE TrainLines(Id INTEGER PRIMARY KEY AUTOINCREMENT,
Number TEXT NOT NULL, LineId INTEGER NOT NULL,
FOREIGN KEY(LineId) REFERENCES Lines(Id));