CREATE TABLE DateCache(Date DATETIME NOT NULL);

CREATE TABLE Lines(Id INTEGER NOT NULL PRIMARY KEY,
Name TEXT NOT NULL);

CREATE TABLE TrainLines(Id INTEGER NOT NULL PRIMARY KEY,
Number TEXT NOT NULL, LineId INTEGER NOT NULL,
FOREIGN KEY(LineId) REFERENCES Lines(id));